### ISSUE TITLE
习题 7.5.3 可以计算出来

### ISSUE THREAD

**Issue by Jason-XII** [RivaJ-github/TheProbabilityLifesaverExerciseAnswer#1]
![image](https://github.com/user-attachments/assets/ac0abeea-a203-47b7-8fef-22df0a5e1420)
我把求和的式子列了出来，利用了公式
![image](https://github.com/user-attachments/assets/714b4c74-58e8-4817-b67c-e42a45cc6a47)
就可以了。
详细一点的过程是，把C_n^k从式子中提出来，剩下一堆组合数相加，把第一项（从k-1个数中选出k-1个数）变成从k个数中选出k个数，然后就可以连锁套上面的公式，结果正好可以把刚才提出去的分母消掉，得到1。
希望您能把这个解法添加进去。这份文档的答案对我很有帮助！

**Comment by RivaJ-github** [comment]
感谢您的关注。下面是根据您的思路不补充的解答：
<img width="660" alt="image" src="https://github.com/user-attachments/assets/a85e0600-91b4-4c05-8b2b-3c27a3ca8b45" />

**Comment by RivaJ-github** [comment]
很抱歉现在才回复您的提案。


很早就收到了您的邮件，但由于个人原因，今天才将您的解法补充到文档中。


非常感谢您的认可，如果有其他的建议，欢迎提交Issue或MR


在 2024年11月23日 21:25，Jason ***@***.***> 写道：


image.png (view on web)
 我把求和的式子列了出来，利用了公式
 image.png (view on web)
 就可以了。
 详细一点的过程是，把C_n^k从式子中提出来，剩下一堆组合数相加，把第一项（从k-1个数中选出k-1个数）变成从k个数中选出k个数，然后就可以连锁套上面的公式，结果正好可以把刚才提出去的分母消掉，得到1。
 希望您能把这个解法添加进去。这份文档的答案对我很有帮助！
